org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=quantified
mod_name=Quantified API
mod_license=BRSSLA V1.3
mod_version=1.0.3
mod_group_id=org.admany.quantified
mod_authors=Admany
mod_description=An advanced API for asynchronous tasks with OpenCL, intelligent caching, and mod networking for Minecraft. License available at: https://github.com/Admany/Quantified-API/blob/master/LICENSE

