org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Forge 1.20.1
minecraft_version_forge_1_20_1=1.20.1
minecraft_version_range_forge_1_20_1=[1.20.1,1.21)
forge_version_forge_1_20_1=47.4.10
forge_version_range_forge_1_20_1=[47,)
loader_version_range_forge_1_20_1=[47,)
mapping_version_forge_1_20_1=1.20.1

# Fabric 1.20.1
minecraft_version_fabric_1_20_1=1.20.1
minecraft_version_range_fabric_1_20_1=>=1.20.1 <1.21
fabric_loader_version=0.16.14
fabric_api_version_1_20_1=0.92.6+1.20.1

# Forge 1.21.1
minecraft_version_forge_1_21_1=1.21.1
minecraft_version_range_forge_1_21_1=[1.21.1,1.22)
forge_version_forge_1_21_1=52.1.14
forge_version_range_forge_1_21_1=[52,)
loader_version_range_forge_1_21_1=[52,)
mapping_version_forge_1_21_1=1.21.1

# Fabric 1.21.1
minecraft_version_fabric_1_21_1=1.21.1
minecraft_version_range_fabric_1_21_1=>=1.21.1 <1.22
fabric_api_version_1_21_1=0.116.11+1.21.1

# NeoForge 1.21.1
minecraft_version_neoforge_1_21_1=1.21.1
minecraft_version_range_neoforge_1_21_1=[1.21.1,1.22)
neoforge_version_1_21_1=21.1.228
neoforge_version_range_1_21_1=[21.1,)
loader_version_range_neoforge_1_21_1=[4,)

mapping_channel=official

mod_id=quantified
mod_name=Quantified API
mod_license=BRSSLA V1.5
mod_version=1.4.4
mod_group_id=org.admany.quantified
mod_authors=Admany
mod_description=Next-gen performance API that aims to unlock the true potential of multithreading with ease. Built to handle insane workloads by utilizing modern hardware to its full extent, while bringing Vulkan-powered GPU acceleration with OpenCL as a fallback for maximum compatibility. License available at: https://github.com/Admany/Quantified-API/blob/master/LICENSE
